DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;


CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM	  DATE,
	 STRASSE         VARCHAR(50),
	 HAUSNR			  VARCHAR(6),			
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50)
    );

CREATE TABLE ZUTAT(
    ZUTATENNR			INTEGER NOT NULL,
    BEZEICHNUNG      VARCHAR(50),
    EINHEIT        	VARCHAR (25),
    NETTOPREIS       DECIMAL(10,2),
    BESTAND          INTEGER,
    LIEFERANT			INTEGER,
	 KALORIEN			INTEGER,
	 KOHLENHYDRATE		DECIMAL (10,2),
	 PROTEIN				DECIMAL(10,2)
);

CREATE TABLE BESTELLUNG (
    BESTELLNR        INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENNR         INTEGER,
    BESTELLDATUM     DATE,
    RECHNUNGSBETRAG  DECIMAL(10,2),
    PRIMARY KEY (BESTELLNR)
);

CREATE TABLE BESTELLUNGZUTAT (
    BESTELLNR       INTEGER NOT NULL,
    ZUTATENNR       INTEGER,
    MENGE     		  INTEGER
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR			  VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON			  VARCHAR(25),
    EMAIL           VARCHAR(50)
);

CREATE TABLE REZEPTE (
    REZEPTNR              INTEGER NOT NULL,
    REZEPTNAME            VARCHAR(50),
    ERNAEHRUNGSKATEGORIE  VARCHAR(20),
    GESAMTPREIS			  DECIMAL (11,2)

);

CREATE TABLE REZEPTINHALT (
    REZEPTNR       INTEGER NOT NULL,
	 ZUTATENNR		 INTEGER,
	 MENGE    		 INTEGER
);		    
   	    	
CREATE TABLE BESTELLTEREZ (
	BESTELLNR 		 INTEGER NOT NULL,
	REZEPTNR 		 INTEGER,
	MENGE  			 INTEGER

);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE REZEPTE ADD PRIMARY KEY (REZEPTNR);
ALTER TABLE ZUTAT ADD PRIMARY KEY (ZUTATENNR);
ALTER TABLE KUNDE ADD PRIMARY KEY (KUNDENNR);
ALTER TABLE LIEFERANT ADD PRIMARY KEY (LIEFERANTENNR);
ALTER TABLE BESTELLUNGZUTAT ADD PRIMARY KEY (BESTELLNR,ZUTATENNR);
ALTER TABLE REZEPTINHALT ADD PRIMARY KEY (REZEPTNR,ZUTATENNR);
ALTER TABLE BESTELLTEREZ ADD PRIMARY KEY (BESTELLNR, REZEPTNR);

/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ZUTAT ADD FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR);
ALTER TABLE BESTELLUNG ADD FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);
ALTER TABLE REZEPTINHALT ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPTE (REZEPTNR);
ALTER TABLE REZEPTINHALT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);
ALTER TABLE BESTELLTEREZ ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR);
ALTER TABLE BESTELLTEREZ ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPTE (REZEPTNR);